######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 7 00:32:50 2013
######################################################################
HEADERS += QtTextEditor.h
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql
# Input
SOURCES += QtTextEditor.cc
