######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 6 11:18:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += QtTextEditor.cc
